version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

  web:
    build: .
    command: bash -c "bundle exec rake db:migrate && bundle exec rails server -b 0.0.0.0 -p 3000"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://myuser:mypassword@db:5432/mydatabase
      - SECRET_KEY_BASE=92ed02cdbe9aba83ddd7c4fe0a4e267444754c5807262a4124a338fdf2a788577ee6011edaab66050ec8e805588bb2c5a4d7b5397b10bbb08e4bb92d7d7d00b3
      - IPSTACK_API_KEY=${IPSTACK_API_KEY}
    networks:
      - app-network

networks:
  app-network:

volumes:
  db_data: